### ISSUE TITLE
SCRAM-SHA-1, SCRAM-SHA-1-PLUS, SCRAM-SHA-256, SCRAM-SHA-256-PLUS

### ISSUE THREAD

**Issue by Neustradamus** [dequbed/rsasl#1]
At this time, the last stable gsasl version supports:
- SCRAM-SHA-1
- SCRAM-SHA-1-PLUS
- SCRAM-SHA-256
- SCRAM-SHA-256-PLUS

Can you add more SCRAM supports?
- https://www.gnu.org/software/gsasl/

**Comment by dequbed** [comment]
The design of gsasl and rsasl means that all mechanisms supported by gsasl are automatically supported by rsasl, so support for SCRAM* already existed.
However there is currently no support for security layers, as for all of my usecases TLS is the better solution. This means that the -PLUS variants aren't supported.

I added a not very good example showing how to perfom a SCRAM-SHA-* exchange, on [client side](https://github.com/dequbed/rsasl/blob/master/examples/scram_client.rs) and [server side](https://github.com/dequbed/rsasl/blob/master/examples/scram_server.rs)

**Comment by Neustradamus** [comment]
@dequbed: Can you add support of -PLUS variants?

RFC9266 has been released: https://tools.ietf.org/html/rfc9266

**Comment by dequbed** [comment]
The current in-development versions (i.e. v2.0.0-*) of rsasl already have full support for arbitrary channel bindings, including the new tls-exporter one.

**Comment by Neustradamus** [comment]
@dequbed: Nice, thanks!
