### ISSUE TITLE
Ensure types that are visible by external crates can be extended without breaking semver.

### ISSUE THREAD

**Issue by dequbed** [dequbed/rsasl#14]
This is mostly important for enums or structs with public fields; exhaustive pattern matching breaks if they are extended without care and haven't been marked correctly (using e.g. `#[non_exhaustive]`).

I would very much apprechiate additional eyes on this one!

This is a good first issue as it only concerns the peripheral API and it's very much not required to know all internal details of rsasl to help with this.

**Comment by Mathieu-Lala** [comment]
I believe these lints are appropriate
https://rust-lang.github.io/rust-clippy/master/#exhaustive_enums
https://rust-lang.github.io/rust-clippy/master/#exhaustive_structs

**Comment by Mathieu-Lala** [comment]
Should I do a PR with them in the `lib.rs` + the fix ?

**Comment by dequbed** [comment]
> I believe these lints are appropriate https://rust-lang.github.io/rust-clippy/master/#exhaustive_enums https://rust-lang.github.io/rust-clippy/master/#exhaustive_structs

I should have guessed that clippy has a lint for that! Thanks for the links :)



> Should I do a PR with them in the `lib.rs` + the fix ?

That would be lovely, yes ^^

**Comment by dequbed** [comment]
I think we can count this issue as fixed now that #19 is merged!

Thanks again to @Mathieu-Lala
