### ISSUE TITLE
Any plan for NTLM support?

### ISSUE THREAD

**Issue by RickSKy** [dequbed/rsasl#21]

**Comment by dequbed** [comment]
I don't plan on adding support for the `NTLM` mechanism to rsasl itself at the moment, for three reasons: 
1. It's considered of 'LIMITED' usage/applicability on the [IANA registry](https://www.iana.org/assignments/sasl-mechanisms/sasl-mechanisms.xhtml), and for now I'd like to concentrate on those marked 'COMMON'.
3. Documentation for the mechanism is *extremely* limited so I would have to resort in large parts to basing my implementation on gsasl code which I feel goes contrary to its license.
2. I don't have a Windows environment to develop it against so my only option would be to test against an existing implementation like e.g. GNU gsasl, which would still leave me unable to debug any issues.

That being said one of the core principles of rsasl is that other crates can add additional mechanism support without having to directly modify rsasl. So, this mechanism could be implemented in a separate crate and if you or anybody else would be interested in writing such a crate I'll be happy to assist.

**Comment by dequbed** [comment]
Addendum: I found the following links that document NTLM authentication and give examples of how it's used in IMAP as SASL mechanism: https://curl.se/rfc/ntlm.html https://davenport.sourceforge.net/ntlm.html (they appear to be mostly the same content so I'm linking both as I don't know which one is the authorative source)

**Comment by dequbed** [comment]
I added this issue to the mechanism support meta-issue, and I will close this issue for the time being. If you or somebody else plans on implementing this mechanism in a downstream crate as custom mechanism for rsasl please leave a comment so I can reopen this issue.
