### ISSUE TITLE
`SessionCallback + 'static` issue

### ISSUE THREAD

**Issue by Mathieu-Lala** [dequbed/rsasl#24]
Hello there 👋 

I had an implementation issue with the `'static` constraint for my callback :

https://github.com/dequbed/rsasl/compare/development...Mathieu-Lala:rsasl:fix/callback-static

What do you think about these changes ?
Is taking a `Box<dyn SessionCallback>` a problem ?

**Comment by dequbed** [comment]
I don't think changing the config builder to take a `Box<dyn SessionCallback>` is a good call. I'd like to later on weaken the trait bounds to allow callbacks living shorter than `'static` and taking a Box would make that change semver-breaking. It also adds an allocation in the IMO rather common case of the callback containing only some database handles and thus being Sized & 'static like so:
```rust
struct DbCallback {
    userdb: DB<User>,
    passdb: DB<Passwords>,
}
```

That being said, you can also implement `SessionCallback` on a `Box<T>` if you defined `T`, so
```rust
struct MyCallback { … }

impl rsasl::callback::SessionCallback for Box<MyCallback> {
    …
}
```
is possible.

I can see the merit of also implementing `SessionCallback` for `Box<dyn SessionCallback>` however, which would need to happen in rsasl itself. I'll add that to the next release, but if you need something like that working right now you can define a wrapper type:
```rust
#[repr(transparent)]
pub struct CallbackWrap(Box<dyn SessionCallback + Send + Sync>);
impl SessionCallback for CallbackWrap {
    fn callback(&self, session_data: &SessionData, context: &Context, request: &mut Request) -> Result<(), SessionError> {
        self.0.callback(session_data, context, request)
    }

    fn validate(&self, session_data: &SessionData, context: &Context, validate: &mut Validate<'_>) -> Result<(), ValidationError> {
        self.0.validate(session_data, context, validate)
    }
}
```
This will be as cheap at runtime as the proper solution and will make upgrading to the next rsasl release painless :)

Does that help you or is your case something I haven't convered here?

**Comment by Mathieu-Lala** [comment]
Thank you for your detailed response!

I will try this on my implementation and let you know if it fix my issue :+1:

**Comment by dequbed** [comment]
Thank you :)

I'll close this issue then for now, please do re-open it if it turns out that my approach doesn't fix your problem ^^
