### ISSUE TITLE
GSSAPI fails to build on macOS

### ISSUE THREAD

**Issue by Kimahriman** [dequbed/rsasl#29]
Using the GSSAPI mechanism fails to build on macOS, it looks like the only way to build libgssapi on macs is to disable the default features: https://github.com/estokes/libgssapi/issues/2

**Comment by dequbed** [comment]
Hey!
Thank you for the report, and sorry for only getting back to you this late ^^'

From reading the linked issue building without default features shouldn't break anything. I don't have a macOS machine ready to test on right now though, so please to tell me if this ends up not working ^^

**Comment by dequbed** [comment]
I've published a version `2.0.1` that contains your fix

**Comment by kezhuw** [comment]
Any plan to publish this `2.0.1` to crates.io ? @dequbed

**Comment by dequbed** [comment]
> Any plan to publish this `2.0.1` to crates.io ? @dequbed

Oh whoops yes of course, it's published now ^^'
