### ISSUE TITLE
SessionCallback::validate() not called for SCRAM mechanism

### ISSUE THREAD

**Issue by mdm** [dequbed/rsasl#4]
I'm using version `2.0.0-preview9`. It seems there is currently no way to extract the authenticated identity after running the SCRAM mechanism successfully on the server side. Comparing with the code for PLAIN I would expect that SCRAM also calls SessionCallback::validate() when it's finished. Is this still missing or is there some other way to extract the identity after authentication?

**Comment by dequbed** [comment]
You're right, SCRAM should call validate the same way PLAIN does.
Fixed that oversight in commit eb433d2 and cut a new release `2.0.0-preview10` with that fix included.

That commit also adds [an example](https://github.com/dequbed/rsasl/blob/main/examples/server_scram.rs) for a server-side SCRAM implementation.

Do re-open this issue if that fix doesn't work for your usecase :)
